# docker-compose.yml
services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"
    shm_size: "2g"

  test-runner:
    build: .
    depends_on:
      - selenium
    environment:
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
      PYTHONPATH: /app     # ✅ Add this line
    volumes:
      - .:/app
    working_dir: /app
    user: "${LOCAL_UID}:${LOCAL_GID}"
