[tool.poetry]
name = "qa-demo-repository"
version = "0.1.0"
description = "Automated UI/API testing setup with pytest, Docker, and Poetry"
authors = ["Jacek Gwoździewicz <gwozdziewiczjacek90@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
selenium = "^4.31.0"
pytest = "^8.3.5"
black = "^25.1.0"
isort = "^6.0.1"
flake8 = "^7.2.0"
mypy = "^1.15.0"
pytest-xdist = "^3.6.0"
pytest-html = "^4.1.1"
pre-commit = "^4.2.0"

[tool.poetry.scripts]
test = "pytest --maxfail=1 --disable-warnings -q"
fmt = "black . && isort ."
lint = "flake8 . && mypy ."