name: Bug report

description: Report a bug with severity level and detailed description.
title: '[BUG] '
labels:
  - bug

body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: |
        Choose how critical this bug is:
        - **Low**: Minor issue, doesn’t affect core functionality.
        - **Medium**: Affects functionality in some cases.
        - **High**: Blocks a key feature or workflow.
        - **Critical**: Prevents release or major data loss.
      options:
        - label: Low
          value: low
          mapping:
            labels: ["severity:low"]
        - label: Medium
          value: medium
          mapping:
            labels: ["severity:medium"]
        - label: High
          value: high
          mapping:
            labels: ["severity:high"]
        - label: Critical
          value: critical
          mapping:
            labels: ["severity:critical"]
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the bug in detail (steps, expected vs. actual behavior, logs, screenshots…).
      placeholder: |
        1. Steps to reproduce…
        2. …

        **Expected behavior:**
        …

        **Actual behavior:**
        …
    validations:
      required: true
