name: Bug report

description: Report a bug with severity level and detailed description.
title: '[BUG] '
labels:
  - bug

body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: |
        Choose how critical this bug is:
        - **Low**: Minor issue, doesn’t affect core functionality.
        - **Medium**: Affects functionality in some cases.
        - **High**: Blocks a key feature or workflow.
        - **Critical**: Prevents release or leads to major data loss.
      options:
        - Low
        - Medium
        - High
        - Critical
    mapping:
      labels:
        Low: ["severity:low"]
        Medium: ["severity:medium"]
        High: ["severity:high"]
        Critical: ["severity:critical"]
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the bug in detail (steps to reproduce, expected vs. actual behavior, logs, screenshots…).
      placeholder: |
        1. Steps to reproduce…
        2. …

        **Expected behavior:**
        …

        **Actual behavior:**
        …
    validations:
      required: true
