name: Bug report
description: Report a bug with severity level.
title: '[BUG] '
labels:
  - bug
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: |
        Choose how critical this bug is:
        - **Low**: Minor issue, doesn’t affect core functionality.
        - **Medium**: Affects functionality in some cases.
        - **High**: Blocks a key feature or workflow.
        - **Critical**: Prevents release or major data loss.
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug details
      description: Describe the problem, steps to reproduce, and any helpful links or screenshots.
      placeholder: |
        1. Steps to reproduce…
        2. …
        
        **Expected behaviour:**  
        …

        **Actual behaviour:**  
        …
